
name: Build and Release

on:
  push:
    branches:
      - custom

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test

      - name: Build project
        run: npm run build

      - name: Generate a unique package version from package.json and commmit id
        id: get_version
        shell: bash
        run: |
          echo "PACKAGE_VERSION=$(node -p 'require("./package.json").version')-${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Set package version from env
        run: npm version $PACKAGE_VERSION --no-git-tag-version
        env:
          PACKAGE_VERSION: ${{ env.PACKAGE_VERSION }}

      - name: Publish to GitHub Packages
        run: npm publish --registry=https://npm.pkg.github.com/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
